version: '3.7'

services:
#   nginx:
#     image: nginx:latest
#     ports:
#       - 8000:80
#     volumes:
#       - ./nginx/nginx.comf:/etc/nginx/conf.d/default.conf
#       - ./src:/var/www/html
#     depends_on:
#       - php

  php:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - '8000:8000'
    # depends_on:
    #   - mysql

  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
